new sphinx version

diff --git a/Makefile.sub b/Makefile.sub
--- a/Makefile.sub
+++ b/Makefile.sub
@@ -25,6 +25,7 @@
 # Warning: Spaces in path or file names are not supported!
 ###################################################################
 MKDIR_P=mkdir -p
+STAMP=touch
 
 # We assume that make is executed from the directory where THIS Makefile
 # is located.
@@ -47,7 +48,7 @@ FRICAS=FRICAS_INITFILE='' fricas -nosman
               -e 's/^.abbrev[ ]*category[ \t]*[A-Z0-9]*[ \t]*/    --C /' \
               -e 's/^.abbrev[ ]*package[ \t]*[A-Z0-9]*[ \t]*/    --P /' \
 	>> projectcompile.input
-	touch $@
+	${STAMP} $@
 
 qetadom.compile: qfunct.compile qetaalg.compile
 qetaqmev.compile: 4ti2.compile qetaauxmeq.compile
@@ -375,50 +376,61 @@ ${ALLINPUT}: %.input: %.out
 ###################################################################
 # General and API documentation
 # Create a HTML site (locally) for the API similar to fricas.github.io/api.
-# The path to the source .spad files.
-SPADSOURCEURL=file:///home/hemmecke/g/qeta/src
-API_SPAD=$(HOME)/g/fricas/src/doc/api.spad
-SPHINX_DIR=sphinx/source
-API_DIR=${SPHINX_DIR}/api
-sphinx/api.spad:
-	if test -r ${API_SPAD}; then cp ${API_SPAD} $@; \
-	else \
-	   G="https://raw.githubusercontent.com/hemmecke/fricas"; \
-	   A="$$G/master-hemmecke/src/doc/api.spad"; \
-	   curl $$A > $@; \
-	fi
-
-abbrev.list: ${patsubst %,%.spad, ${SPADFILES}}
+abbrev-lines.list: ${patsubst %,%.spad, ${SPADFILES}}
 	(cd ${ROOT}/src; \
 	grep -nH '^.*$$' $^ \
 	| awk '/:[)]if (LiterateDoc|false) *$$/,/:[)]endif/ {next}; /:[)]abbrev / {gsub(/[.:]/," "); print $$1, $$3, $$5, $$6, $$7}') > $@
 
-${API_DIR}/history.rst:
-	$(MKDIR_P) ${API_DIR}
-	echo "Commit History" > $@
-	echo "==============" >>$@
-	echo                  >>$@
-	echo ".. code::"      >>$@
-	echo                  >>$@
-	(cd ${ROOT}; git log --decorate master^^^..HEAD | sed 's/^/    /') >> $@
-
-sphinx/stamp: abbrev.list ${API_DIR}/history.rst
-	${MAKE} sphinx/api.spad
-	$(MKDIR_P) ${API_DIR}
-	((echo ')compile sphinx/api.spad'; \
-	  echo ')read projectlibs'; \
-	  echo ")cd ${API_DIR}"; \
-	  echo 'documentAll("../../../abbrev.list")') \
-	  | FRICAS_INITFILE='' fricas -nosman) > $@
-	sed -i 's/:maxdepth: 1/:maxdepth: 2/; /|PACKAGE_DOC_HOME|/d' ${API_DIR}/index.rst
-
-mysphinx: sphinx/stamp
-	. ${VIRTUALENV}/sphinx/bin/activate && cd sphinx && make html
-
-html: compile-spad
+###################################################################
+# Copy the sphinx sources into the tmp directory
+# The path to the source .spad files.
+API_SPAD=$(HOME)/g/fricas/src/doc/api.spad
+API_DIR=sphinx/source/api
+stamp-sphinx: ${ROOT}/sphinx/source/conf.py
 	-rm -rf sphinx
 	cp -r ${ROOT}/sphinx .
-	${MAKE} mysphinx
+	if test -r ${API_SPAD}; then cp ${API_SPAD} sphinx/api.spad; \
+	else \
+	   G="https://raw.githubusercontent.com/hemmecke/fricas"; \
+	   A="$$G/formatted/src/doc/api.spad"; \
+	   curl $$A > sphinx/api.spad; \
+	fi
+	${STAMP} $@
+
+# Generate the API documentation into ${API_DIR}/*.rst files.
+stamp-api: abbrev-lines.list stamp-sphinx compile-spad
+	-rm -rf sphinx/build ${API_DIR}
+	$(MKDIR_P) ${API_DIR}
+	((echo ')compile "sphinx/api.spad"'; \
+	  echo ')read projectlibs'; \
+	  echo ")cd ${API_DIR}"; \
+	  echo 'documentAll("${ROOT}/tmp/$<")') \
+	  | $(FRICAS)) > $@
+
+# Call sphinx-build to compile the .rst files into .html files.
+stamp-html: stamp-api
+	sphinx-build --version \
+	|| (echo "==> sphinx-build not found. Please install it."; exit 1)
+	cd sphinx && ${MAKE} html
+	${STAMP} $@
+
+# Copy the generated html directory into the target place and include
+# book.pdf.
+stamp-doc: stamp-html
+	-rm -rf ${ROOT}/html
+	cp -R sphinx/build/html ${ROOT}
+	${STAMP} $@
+
+doc: stamp-doc
+
+# The following target makes links point to the local repository.
+# Might be useful for development without internet connection.
+localdoc:
+	${MAKE} PACKAGE_SOURCE_VIEW=file://${ROOT} stamp-doc
+
+clean-html:
+	-rm -rf ${ROOT}/html sphinx
+	-rm -rf stamp-sphinx stamp-api stamp-html stamp-doc
 
 # Update the gh-pages branch.
 GHPAGES=/tmp/qeta_gh-pages
